--- Icon Registry - shared octicon loading and inline SVG rendering
--- @module icons
--- @license MIT
--- @copyright 2026 Mickaël Canouil
--- @author Mickaël Canouil
--- @brief Loads the embedded octicon set (octicons.json, generated by
--- tools/generate-octicons.py) and a small hand-maintained set of brand icons
--- octicons doesn't cover (currently: the GitLab logo). Shared by the widget
--- (which builds SVG elements client-side from the raw path data) and the
--- gitlink filter's platform/status badges (which render inline SVG markup
--- server-side).

local M = {}

--- Load a sibling module from the same directory as this file.
--- @param filename string The sibling module filename (e.g., 'string.lua')
--- @return table The loaded module
local function load_sibling(filename)
  local source = debug.getinfo(1, 'S').source:sub(2)
  local dir = source:match('(.*[/\\])') or ''
  return require((dir .. filename):gsub('%.lua$', ''))
end

local str = load_sibling('string.lua')
local log = load_sibling('logging.lua')

--- @type table<string, table>|nil Octicon path data by name (loaded once per render)
local octicons_cache = nil

--- @type table<string, table> Hand-maintained icons octicons.json doesn't cover:
--- brand marks for non-GitHub platforms. Each entry has its own `native_size`
--- (the square coordinate space its path data is authored in) since these
--- aren't drawn on octicons' fixed 16x16 grid.
local EXTRA_ICONS = {
  gitlab = {
    native_size = 24,
    paths = {
      {
        d = 'm23.6004 9.5927-.0337-.0862L20.3.9814a.851.851 0 0 0-.3362-.405.8748.8748 0 0 0-.9997.0539.8748.8748 0 0 0-.29.4399l-2.2055 6.748H7.5375l-2.2057-6.748a.8573.8573 0 0 0-.29-.4412.8748.8748 0 0 0-.9997-.0537.8585.8585 0 0 0-.3362.4049L.4332 9.5015l-.0325.0862a6.0657 6.0657 0 0 0 2.0119 7.0105l.0113.0087.03.0213 4.976 3.7264 2.462 1.8633 1.4995 1.1321a1.0085 1.0085 0 0 0 1.2197 0l1.4995-1.1321 2.4619-1.8633 5.006-3.7489.0125-.01a6.0682 6.0682 0 0 0 2.0094-7.003z',
      },
    },
  },
}

--- Load the embedded octicon set (octicons.json). Only the icons actually
--- used on a given page/element are ever rendered into the output, so the
--- full set never reaches the rendered page.
--- @param extension_name string The extension name (for warnings)
--- @return table<string, table> Octicon path data by name
function M.load_octicons(extension_name)
  if octicons_cache then
    return octicons_cache
  end
  octicons_cache = {}
  local path = quarto.utils.resolve_path('octicons.json')
  local file = io.open(path, 'r')
  if not file then
    log.log_warning(
      extension_name,
      "Missing 'octicons.json': icons fall back to text/Bootstrap names only. " ..
      'Regenerate it with tools/generate-octicons.py.'
    )
    return octicons_cache
  end
  local content = file:read('*all')
  file:close()
  local ok, decoded = pcall(quarto.json.decode, content)
  if ok and type(decoded) == 'table' then
    octicons_cache = decoded
  else
    log.log_warning(
      extension_name,
      "Failed to parse 'octicons.json': icons fall back to text/Bootstrap names only."
    )
  end
  return octicons_cache
end

--- Look up an icon's path data and native coordinate size by name, checking
--- the embedded octicon set first, then the hand-maintained brand-icon extras.
--- @param name string The icon name (e.g. "mark-github", "gitlab", "issue-opened")
--- @param extension_name string The extension name (for warnings)
--- @return table|nil paths List of {d, ["fill-rule"]} path attribute objects, or nil if not found
--- @return integer native_size The square coordinate space the path data is authored in (octicons: 16)
function M.get_icon(name, extension_name)
  local extra = EXTRA_ICONS[name]
  if extra then
    return extra.paths, extra.native_size
  end
  local octicons = M.load_octicons(extension_name)
  local paths = octicons[name]
  if paths then
    return paths, 16
  end
  return nil, 16
end

--- Render an icon as an inline SVG string for server-side HTML embedding
--- (e.g. inside a `pandoc.RawInline('html', ...)`). Uses `currentColor` so the
--- icon follows the surrounding text/badge colour unless overridden by the caller.
---
--- Deliberately has no `viewBox`: Quarto's post-render HTML pass doesn't
--- implement the HTML5 "adjust SVG attributes" step, so a `viewBox` written
--- here comes out as the invalid, ignored `viewbox`, and CSS-resizing an
--- `<svg>` with no working viewBox crops it rather than scaling it (the
--- viewport shrinks but 1 path unit still equals 1px, so anything past the
--- new edge is simply cut off). Icons authored on a grid other than
--- octicons' 16x16 (currently just the GitLab logo, 24x24) are instead
--- rescaled onto that grid with `<g transform="scale(...)">` — `transform`
--- is already all-lowercase, so it survives the HTML5 case-folding intact —
--- and the desired display size is reached the same way, so every icon ends
--- up correctly scaled with plain `width`/`height` attributes and no viewBox.
--- @param name string The icon name (see `get_icon`)
--- @param size integer Desired display width/height in pixels
--- @param extension_name string The extension name (for warnings)
--- @return string|nil The `<svg>...</svg>` markup, or nil if the icon isn't known
function M.render_icon_svg(name, size, extension_name)
  local paths, native_size = M.get_icon(name, extension_name)
  if not paths then
    return nil
  end
  local path_markup = {}
  for _, path in ipairs(paths) do
    local fill_rule = path['fill-rule']
    local fill_rule_attr = fill_rule and (' fill-rule="' .. str.escape_attribute(fill_rule) .. '"') or ''
    table.insert(path_markup, '<path d="' .. str.escape_attribute(path.d) .. '"' .. fill_rule_attr .. '/>')
  end
  local body = table.concat(path_markup)
  local scale = size / native_size
  if scale ~= 1 then
    body = '<g transform="scale(' .. tostring(scale) .. ')">' .. body .. '</g>'
  end
  return '<svg width="' .. size .. '" height="' .. size ..
      '" fill="currentColor" aria-hidden="true" focusable="false" style="display:block;">' ..
      body .. '</svg>'
end

return M
